# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       libdrm

# >> macros
# << macros

Summary:    Direct Rendering Manager runtime library
Version:    2.4.46
Release:    1
Group:      System/Libraries
License:    MIT
URL:        http://dri.sourceforge.net
Source0:    http://dri.freedesktop.org/libdrm/%{name}-%{version}.tar.bz2
Source100:  libdrm.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(pciaccess) >= 0.10
BuildRequires:  pkgconfig(pthread-stubs)
BuildRequires:  pkgconfig(udev)

%description
%{summary}


%package radeon
Summary:    Direct Rendering Manager radeon api
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description radeon
%{summary}.


%package devel
Summary:    Direct Rendering Manager development package
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   %{name}-radeon = %{version}-%{release}
Requires:   kernel-headers

%description devel
%{summary}.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
unset LD_AS_NEEDED
# >> build pre
cd libdrm
# << build pre

%reconfigure --disable-static \
    --disable-intel \
    --disable-nouveau \
    --disable-vmwgfx

make %{?jobs:-j%jobs}

# >> build post
cd ..
# << build post

%install
rm -rf %{buildroot}
# >> install pre
cd libdrm
# << install pre
%make_install

# >> install post
cd ..
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%post radeon -p /sbin/ldconfig

%postun radeon -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%{_libdir}/libdrm.so.*
%{_libdir}/libkms.so.*
# >> files
# << files

%files radeon
%defattr(-,root,root,-)
%{_libdir}/libdrm_radeon.so.*
# >> files radeon
# << files radeon

%files devel
%defattr(-,root,root,-)
%{_includedir}/libdrm/*.h
%{_includedir}/*.h
%{_libdir}/lib*.so
%{_libdir}/pkgconfig/*.pc
%{_includedir}/libkms/*.h
# >> files devel
# << files devel
